name: Matrix
on: push
jobs:
    node-version:
      strategy:
        matrix:
          node-version: [6,8,10]
        fail-fast: true
      runs-on: ubuntu-latest
      steps:
        - name: Log node version
          run: node -v
        - uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-verson }}
        - name: Log node version again
          run: node -v
